// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxiYLncl0hpXwxkoQzJfUg-qt0S9US_TM',
    appId: '1:3293889581:web:9b6eab52542addd5b964a4',
    messagingSenderId: '3293889581',
    projectId: 'dictionary-45478',
    authDomain: 'dictionary-45478.firebaseapp.com',
    storageBucket: 'dictionary-45478.appspot.com',
    measurementId: 'G-F8T13BTQ7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr4IMCjVyZd7kQ_RhuKgjq_uSoEYLugRc',
    appId: '1:3293889581:android:28abbe4a7ea6bf8bb964a4',
    messagingSenderId: '3293889581',
    projectId: 'dictionary-45478',
    storageBucket: 'dictionary-45478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGAsqLCSZr_u0BWqjJ8UZLdl7plunL8l4',
    appId: '1:3293889581:ios:6b2cf9c1335c00d3b964a4',
    messagingSenderId: '3293889581',
    projectId: 'dictionary-45478',
    storageBucket: 'dictionary-45478.appspot.com',
    iosClientId: '3293889581-h68qg563vbe0trm0q83t5b8000o8f402.apps.googleusercontent.com',
    iosBundleId: 'com.example.dictionary',
  );
}
